# Generated by Django 3.1.7 on 2021-03-20 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='moderator',
            new_name='is_moderator',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='username',
        ),
    ]
