# Generated by Django 3.1.7 on 2021-03-20 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0002_auto_20210320_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
